![Kali](https://skillicons.dev/icons?i=kalilinux)
![Linux](https://skillicons.dev/icons?i=linux)
![Windows](https://skillicons.dev/icons?i=windows)
![Bash](https://skillicons.dev/icons?i=bash)
![Docker](https://skillicons.dev/icons?i=docker)
![WordPress](https://skillicons.dev/icons?i=wordpress)
